(function(){
  const common={
    en:{updated:'Last updated: August 24, 2026',home:'✦ PictTool',privacy:'Privacy Policy',refund:'Refund Policy',terms:'Terms of Service'},
    zh:{updated:'最后更新：2026年8月24日',home:'✦ PictTool',privacy:'隐私政策',refund:'退款政策',terms:'服务条款'},
    es:{updated:'Última actualización: 24 de agosto de 2026',home:'✦ PictTool',privacy:'Política de privacidad',refund:'Política de reembolsos',terms:'Términos del servicio'},
    fr:{updated:'Dernière mise à jour : 24 août 2026',home:'✦ PictTool',privacy:'Politique de confidentialité',refund:'Politique de remboursement',terms:'Conditions d’utilisation'},
    pt:{updated:'Última atualização: 24 de agosto de 2026',home:'✦ PictTool',privacy:'Política de privacidade',refund:'Política de reembolso',terms:'Termos de serviço'},
    ja:{updated:'最終更新日：2026年8月24日',home:'✦ PictTool',privacy:'プライバシーポリシー',refund:'返金ポリシー',terms:'利用規約'},
    ko:{updated:'최종 업데이트: 2026년 8월 24일',home:'✦ PictTool',privacy:'개인정보 처리방침',refund:'환불 정책',terms:'서비스 약관'},
    ar:{updated:'آخر تحديث: 24 أغسطس 2026',home:'✦ PictTool',privacy:'سياسة الخصوصية',refund:'سياسة رد الأموال',terms:'شروط الخدمة'},
    de:{updated:'Zuletzt aktualisiert: 24. August 2026',home:'✦ PictTool',privacy:'Datenschutzerklärung',refund:'Erstattungsrichtlinie',terms:'Nutzungsbedingungen'}
  };
  const t=(intro,sections)=>({intro,sections});
  const policies={
    terms:{
      en:t('These Terms govern your use of PictTool, an online service providing AI image generation and image-editing tools.',[['1. Use of the service','You may use PictTool only in compliance with applicable laws and these Terms. You must not create or distribute unlawful, fraudulent, infringing, abusive, or harmful content, or interfere with the service or its security.'],['2. Accounts and subscriptions','Some features may require an account. You are responsible for keeping your account information secure. Pict Pro is a recurring subscription priced at US$9 per month and includes 300 credits per billing month. The subscription renews automatically until cancelled.'],['3. Credits and content','Credits are digital usage units for eligible AI image-generation and editing features. Credits have no cash value, are non-transferable, and are subject to the limits shown in the service. You are responsible for the images and prompts you submit and must have the rights needed to use them.'],['4. Intellectual property','PictTool and its software, design, and branding are owned by their respective owners. Subject to these Terms and applicable law, you may use outputs generated through the service for lawful personal or commercial purposes. AI outputs may not be unique.'],['5. Availability and changes','The service is provided on an as-available basis. We may change, suspend, or discontinue features and may update these Terms when necessary.'],['6. Contact','For questions about these Terms or your account, use the Feedback form available on PictTool.']]),
      zh:t('本服务条款适用于您对 PictTool 的使用。PictTool 是提供 AI 图像生成和图片编辑工具的在线服务。',[['1. 服务使用','您只能在遵守适用法律和本条款的前提下使用 PictTool。不得创建或传播违法、欺诈、侵权、辱骂或有害内容，也不得干扰服务或其安全性。'],['2. 账户和订阅','部分功能可能需要账户。您应负责保护账户信息安全。Pict Pro 为每月 9 美元的自动续费订阅，每个计费月包含 300 点数，除非取消，否则会自动续费。'],['3. 点数和内容','点数是用于符合条件的 AI 生图和编辑功能的数字使用单位，不具有现金价值且不可转让，并受服务页面显示的限制约束。您应确保提交的图片和提示词拥有必要的使用权。'],['4. 知识产权','PictTool 及其软件、设计和品牌归其相应权利人所有。在遵守本条款和适用法律的前提下，您可以将服务生成的结果用于合法的个人或商业用途。AI 生成结果可能并不唯一。'],['5. 服务可用性和变更','服务按现状和可用情况提供。我们可能变更、暂停或停止部分功能，并在必要时更新本条款。'],['6. 联系我们','如对本条款或账户有疑问，请使用 PictTool 上的意见反馈表单。']]),
      es:t('Estas condiciones regulan el uso de PictTool, un servicio en línea de generación y edición de imágenes con IA.',[['1. Uso del servicio','Solo puede usar PictTool de acuerdo con la ley y estas condiciones. No cree ni distribuya contenido ilegal, fraudulento, infractor, abusivo o dañino, ni interfiera con el servicio o su seguridad.'],['2. Cuentas y suscripciones','Algunas funciones requieren una cuenta. Debe proteger sus datos de acceso. Pict Pro cuesta US$9 al mes, incluye 300 créditos por periodo de facturación y se renueva automáticamente hasta su cancelación.'],['3. Créditos y contenido','Los créditos son unidades digitales de uso, no tienen valor en efectivo ni pueden transferirse. Usted es responsable de las imágenes y solicitudes que envíe y de contar con los derechos necesarios.'],['4. Propiedad intelectual','PictTool, su software, diseño y marca pertenecen a sus respectivos titulares. Puede usar legalmente los resultados generados, aunque no se garantiza que sean únicos.'],['5. Disponibilidad y cambios','El servicio se ofrece según disponibilidad. Podemos modificar, suspender o retirar funciones y actualizar estas condiciones cuando sea necesario.'],['6. Contacto','Para preguntas sobre estas condiciones o su cuenta, use el formulario de comentarios de PictTool.']]),
      fr:t('Les présentes conditions régissent votre utilisation de PictTool, un service en ligne de génération et de retouche d’images par IA.',[['1. Utilisation du service','Vous devez utiliser PictTool conformément à la loi et aux présentes conditions. Il est interdit de créer ou diffuser du contenu illégal, frauduleux, contrefaisant, abusif ou nuisible, ou de compromettre le service et sa sécurité.'],['2. Comptes et abonnements','Certaines fonctions nécessitent un compte. Vous devez protéger vos informations de compte. Pict Pro coûte 9 USD par mois, comprend 300 crédits par période de facturation et se renouvelle automatiquement jusqu’à résiliation.'],['3. Crédits et contenu','Les crédits sont des unités d’utilisation numériques sans valeur monétaire et non transférables. Vous êtes responsable des images et demandes envoyées et des droits nécessaires à leur utilisation.'],['4. Propriété intellectuelle','PictTool, son logiciel, son design et sa marque appartiennent à leurs titulaires. Vous pouvez utiliser légalement les résultats générés, qui peuvent ne pas être uniques.'],['5. Disponibilité et changements','Le service est fourni selon sa disponibilité. Nous pouvons modifier, suspendre ou retirer des fonctions et mettre à jour ces conditions si nécessaire.'],['6. Contact','Pour toute question, utilisez le formulaire de commentaires de PictTool.']]),
      pt:t('Estes termos regem o uso do PictTool, um serviço online de geração e edição de imagens com IA.',[['1. Uso do serviço','Use o PictTool somente de acordo com a lei e estes termos. Não crie nem distribua conteúdo ilegal, fraudulento, infrator, abusivo ou prejudicial, nem interfira no serviço ou em sua segurança.'],['2. Contas e assinaturas','Alguns recursos exigem uma conta. Você deve proteger seus dados. O Pict Pro custa US$9 por mês, inclui 300 créditos por período e é renovado automaticamente até o cancelamento.'],['3. Créditos e conteúdo','Créditos são unidades digitais de uso, sem valor em dinheiro e intransferíveis. Você é responsável pelas imagens e solicitações enviadas e pelos direitos necessários para usá-las.'],['4. Propriedade intelectual','O PictTool, seu software, design e marca pertencem aos respectivos titulares. Os resultados gerados podem ser usados legalmente, mas podem não ser exclusivos.'],['5. Disponibilidade e alterações','O serviço é oferecido conforme a disponibilidade. Podemos alterar, suspender ou descontinuar recursos e atualizar estes termos quando necessário.'],['6. Contato','Para dúvidas, use o formulário de feedback do PictTool.']]),
      ja:t('本規約は、AI画像生成・編集ツールを提供するオンラインサービス PictTool の利用に適用されます。',[['1. サービスの利用','PictTool は、適用法令と本規約を守って利用してください。違法、詐欺的、侵害的、 abusive または有害なコンテンツの作成・配布、サービスやセキュリティへの干渉は禁止です。'],['2. アカウントとサブスクリプション','一部の機能にはアカウントが必要です。アカウント情報は安全に管理してください。Pict Pro は月額9米ドルで、各請求期間に300クレジットが含まれ、解約まで自動更新されます。'],['3. クレジットとコンテンツ','クレジットは対象機能のデジタル利用単位で、現金価値はなく譲渡できません。送信する画像やプロンプトと、その利用権については利用者が責任を負います。'],['4. 知的財産','PictTool、ソフトウェア、デザイン、ブランドは各権利者に帰属します。生成結果は法令の範囲で個人・商用利用できますが、唯一性は保証されません。'],['5. 可用性と変更','サービスは提供可能な範囲で提供されます。機能を変更・停止・終了し、必要に応じて本規約を更新することがあります。'],['6. 連絡先','本規約やアカウントについては、PictTool のフィードバックフォームをご利用ください。']]),
      ko:t('본 약관은 AI 이미지 생성 및 편집 도구를 제공하는 온라인 서비스 PictTool의 이용에 적용됩니다.',[['1. 서비스 이용','관련 법률과 본 약관을 준수하여 PictTool을 이용해야 합니다. 불법적·사기성·침해성·유해한 콘텐츠를 만들거나 배포하고 서비스 또는 보안을 방해해서는 안 됩니다.'],['2. 계정 및 구독','일부 기능에는 계정이 필요합니다. 계정 정보를 안전하게 관리해야 합니다. Pict Pro는 월 US$9이며 결제 기간마다 300크레딧을 제공하고 취소할 때까지 자동 갱신됩니다.'],['3. 크레딧 및 콘텐츠','크레딧은 대상 기능의 디지털 사용 단위로 현금 가치가 없고 양도할 수 없습니다. 제출하는 이미지와 프롬프트 및 필요한 이용 권리는 이용자에게 책임이 있습니다.'],['4. 지식재산권','PictTool과 소프트웨어, 디자인, 브랜드는 각 권리자에게 귀속됩니다. 생성 결과는 법이 허용하는 범위에서 사용할 수 있지만 고유성이 보장되지는 않습니다.'],['5. 이용 가능성 및 변경','서비스는 제공 가능한 범위에서 제공됩니다. 필요에 따라 기능을 변경·중단·종료하거나 약관을 업데이트할 수 있습니다.'],['6. 문의','약관이나 계정에 관한 문의는 PictTool 피드백 양식을 이용해 주세요.']]),
      ar:t('تحكم هذه الشروط استخدامك لـ PictTool، وهي خدمة عبر الإنترنت لإنشاء الصور وتحريرها بالذكاء الاصطناعي.',[['1. استخدام الخدمة','يجب استخدام PictTool وفق القوانين المعمول بها وهذه الشروط. يُمنع إنشاء أو توزيع محتوى غير قانوني أو احتيالي أو منتهك أو مسيء أو ضار، أو تعطيل الخدمة أو أمنها.'],['2. الحسابات والاشتراكات','قد تتطلب بعض الميزات حساباً. أنت مسؤول عن حماية معلومات حسابك. تبلغ تكلفة Pict Pro ‏9 دولارات شهرياً وتشمل 300 رصيد لكل فترة فوترة وتتجدد تلقائياً حتى الإلغاء.'],['3. الأرصدة والمحتوى','الأرصدة وحدات استخدام رقمية بلا قيمة نقدية وغير قابلة للتحويل. أنت مسؤول عن الصور والمطالبات التي ترسلها وعن امتلاك حقوق استخدامها.'],['4. الملكية الفكرية','تعود ملكية PictTool وبرمجياتها وتصميمها وعلامتها إلى أصحاب الحقوق المعنيين. يمكنك استخدام النتائج المولدة بشكل قانوني، لكنها قد لا تكون فريدة.'],['5. التوفر والتغييرات','تقدم الخدمة حسب التوفر. قد نغير الميزات أو نعلقها أو نوقفها ونحدث هذه الشروط عند الحاجة.'],['6. التواصل','للاستفسارات، استخدم نموذج الملاحظات في PictTool.']]),
      de:t('Diese Bedingungen regeln die Nutzung von PictTool, einem Onlinedienst zur KI-Bilderstellung und -bearbeitung.',[['1. Nutzung des Dienstes','Nutzen Sie PictTool nur im Einklang mit geltendem Recht und diesen Bedingungen. Illegale, betrügerische, rechtsverletzende, missbräuchliche oder schädliche Inhalte sowie Eingriffe in Dienst oder Sicherheit sind verboten.'],['2. Konten und Abonnements','Einige Funktionen erfordern ein Konto. Sie müssen Ihre Kontodaten schützen. Pict Pro kostet 9 US-Dollar pro Monat, enthält 300 Credits pro Abrechnungszeitraum und verlängert sich bis zur Kündigung automatisch.'],['3. Credits und Inhalte','Credits sind digitale Nutzungseinheiten ohne Geldwert und nicht übertragbar. Für eingereichte Bilder, Eingaben und die erforderlichen Nutzungsrechte sind Sie verantwortlich.'],['4. Geistiges Eigentum','PictTool, Software, Design und Marke gehören den jeweiligen Rechteinhabern. Generierte Ergebnisse dürfen rechtmäßig privat oder kommerziell genutzt werden, sind aber möglicherweise nicht einzigartig.'],['5. Verfügbarkeit und Änderungen','Der Dienst wird nach Verfügbarkeit bereitgestellt. Wir können Funktionen ändern, aussetzen oder einstellen und diese Bedingungen bei Bedarf aktualisieren.'],['6. Kontakt','Bei Fragen nutzen Sie das Feedback-Formular von PictTool.']])
    },
    privacy:{
      en:t('This Privacy Policy explains how PictTool handles information when you use our website and services.',[['1. Information we collect','We may collect your email address when you create or use an account, subscribe to updates, submit feedback, or purchase Pict Pro. We may also collect basic technical information such as browser, device, language, approximate location, and usage events.'],['2. Images and prompts','Images and prompts are processed to provide the tool you request. We do not use uploaded images to identify you or sell them. Do not upload sensitive, personal, or confidential material.'],['3. Payments','Payments and subscription management are handled by Paddle. Paddle may process payment, billing, and transaction information under its own privacy policy. PictTool does not receive your full payment-card number.'],['4. How we use information','We use information to provide and secure the service, process subscriptions, respond to requests, improve performance, prevent abuse, and send updates when you subscribe.'],['5. Sharing and retention','We share information with service providers that help us host, authenticate, analyze, process, and bill the service. We retain information only as reasonably needed for these purposes, legal obligations, and disputes.'],['6. Your choices and contact','You may request access to or deletion of account information through the PictTool feedback form. You can cancel marketing emails through their unsubscribe option.']]),
      zh:t('本隐私政策说明您使用 PictTool 网站和服务时，我们如何处理相关信息。',[['1. 我们收集的信息','当您创建或使用账户、订阅更新、提交反馈或购买 Pict Pro 时，我们可能收集您的邮箱地址，也可能收集浏览器、设备、语言、大致位置和使用事件等基础技术信息。'],['2. 图片和提示词','图片和提示词会被处理，以提供您请求的工具功能。我们不会利用上传的图片识别您或出售图片。请勿上传敏感、个人或机密内容。'],['3. 支付','支付和订阅管理由 Paddle 处理。Paddle 可能依据其隐私政策处理支付、账单和交易信息。PictTool 不会收到您的完整银行卡号。'],['4. 信息用途','我们使用信息来提供和保护服务、处理订阅、回复请求、改进性能、防止滥用，以及在您订阅后发送更新。'],['5. 共享和保存','我们会与帮助我们托管、认证、分析、处理和收费的服务提供商共享必要信息。信息只会在业务、法律义务和争议处理所需的合理期限内保存。'],['6. 您的选择和联系','您可以通过 PictTool 反馈表单请求访问或删除账户信息，也可以使用营销邮件中的退订选项取消邮件。']]),
      es:t('Esta política explica cómo PictTool trata la información cuando utiliza nuestro sitio y servicios.',[['1. Información que recopilamos','Podemos recopilar su correo al crear o usar una cuenta, suscribirse a novedades, enviar comentarios o comprar Pict Pro. También podemos recopilar datos técnicos básicos como navegador, dispositivo, idioma, ubicación aproximada y eventos de uso.'],['2. Imágenes y solicitudes','Procesamos imágenes y solicitudes para prestar la herramienta elegida. No usamos las imágenes subidas para identificarle ni las vendemos. No suba contenido sensible, personal o confidencial.'],['3. Pagos','Paddle gestiona los pagos y suscripciones y puede procesar datos de pago, facturación y transacciones según su propia política. PictTool no recibe el número completo de su tarjeta.'],['4. Uso de la información','Usamos la información para prestar y proteger el servicio, procesar suscripciones, responder, mejorar el rendimiento, prevenir abusos y enviar novedades solicitadas.'],['5. Compartición y conservación','Compartimos la información necesaria con proveedores que nos ayudan a alojar, autenticar, analizar, procesar y cobrar. La conservamos solo durante el tiempo razonablemente necesario.'],['6. Sus opciones y contacto','Puede solicitar acceso o eliminación de su cuenta mediante el formulario de comentarios y cancelar correos de marketing con el enlace de baja.']]),
      fr:t('Cette politique explique comment PictTool traite les informations lorsque vous utilisez notre site et nos services.',[['1. Informations collectées','Nous pouvons recueillir votre adresse e-mail lorsque vous créez ou utilisez un compte, vous abonnez aux nouveautés, envoyez un commentaire ou achetez Pict Pro. Des données techniques de base peuvent également être recueillies.'],['2. Images et demandes','Les images et demandes sont traitées pour fournir l’outil demandé. Nous n’utilisons pas les images importées pour vous identifier et ne les vendons pas. N’importez pas de contenu sensible ou confidentiel.'],['3. Paiements','Paddle gère les paiements et abonnements et peut traiter les données de paiement, de facturation et de transaction selon sa propre politique. PictTool ne reçoit pas le numéro complet de votre carte.'],['4. Utilisation','Nous utilisons les informations pour fournir et sécuriser le service, traiter les abonnements, répondre, améliorer les performances, prévenir les abus et envoyer les mises à jour demandées.'],['5. Partage et conservation','Nous partageons les informations nécessaires avec les prestataires qui nous aident à héberger, authentifier, analyser, traiter et facturer. Nous les conservons pendant la durée raisonnablement nécessaire.'],['6. Vos choix et contact','Vous pouvez demander l’accès ou la suppression de votre compte via le formulaire de commentaires et vous désabonner des e-mails marketing.']]),
      pt:t('Esta política explica como o PictTool trata informações quando você usa nosso site e serviços.',[['1. Informações coletadas','Podemos coletar seu e-mail ao criar ou usar uma conta, assinar novidades, enviar feedback ou comprar o Pict Pro. Também podemos coletar dados técnicos básicos, como navegador, dispositivo, idioma, localização aproximada e eventos de uso.'],['2. Imagens e solicitações','Imagens e solicitações são processadas para fornecer a ferramenta pedida. Não usamos imagens enviadas para identificar você nem as vendemos. Não envie conteúdo sensível, pessoal ou confidencial.'],['3. Pagamentos','Pagamentos e assinaturas são tratados pelo Paddle, que pode processar dados de pagamento, cobrança e transação conforme sua política. O PictTool não recebe o número completo do cartão.'],['4. Uso das informações','Usamos informações para fornecer e proteger o serviço, processar assinaturas, responder, melhorar o desempenho, evitar abusos e enviar atualizações solicitadas.'],['5. Compartilhamento e retenção','Compartilhamos informações necessárias com fornecedores que ajudam a hospedar, autenticar, analisar, processar e cobrar. Mantemos os dados apenas pelo tempo razoavelmente necessário.'],['6. Suas escolhas e contato','Você pode solicitar acesso ou exclusão da conta pelo formulário de feedback e cancelar e-mails de marketing pelo link de cancelamento.']]),
      ja:t('このポリシーは、PictTool のウェブサイトとサービス利用時に情報をどのように扱うかを説明します。',[['1. 収集する情報','アカウントの作成・利用、更新の購読、フィードバックの送信、Pict Pro の購入時にメールアドレスを収集することがあります。ブラウザ、端末、言語、おおよその位置、利用イベントなどの技術情報も収集する場合があります。'],['2. 画像とプロンプト','画像とプロンプトは、依頼された機能を提供するために処理されます。アップロード画像で個人を特定したり、販売したりしません。機密・個人的な内容はアップロードしないでください。'],['3. 支払い','支払いとサブスクリプションは Paddle が処理します。PictTool は完全なカード番号を受け取りません。'],['4. 情報の利用','サービスの提供・保護、購読処理、問い合わせへの対応、改善、乱用防止、購読した更新情報の送信に利用します。'],['5. 共有と保存','ホスティング、認証、分析、処理、請求を支援する事業者と必要な情報を共有します。情報は必要な期間だけ保存します。'],['6. 選択と連絡','PictTool のフィードバックフォームからアカウント情報の確認・削除を依頼できます。マーケティングメールは配信停止リンクから解除できます。']]),
      ko:t('이 개인정보 처리방침은 PictTool 웹사이트와 서비스를 이용할 때 정보를 처리하는 방법을 설명합니다.',[['1. 수집 정보','계정 생성·사용, 업데이트 구독, 피드백 제출 또는 Pict Pro 구매 시 이메일을 수집할 수 있습니다. 브라우저, 기기, 언어, 대략적인 위치 및 사용 이벤트 같은 기본 기술 정보도 수집할 수 있습니다.'],['2. 이미지 및 프롬프트','요청한 도구를 제공하기 위해 이미지와 프롬프트를 처리합니다. 업로드한 이미지로 사용자를 식별하거나 판매하지 않습니다. 민감하거나 개인적인 자료는 업로드하지 마세요.'],['3. 결제','결제와 구독은 Paddle이 처리하며 자체 개인정보 처리방침에 따라 결제·청구·거래 정보를 처리할 수 있습니다. PictTool은 전체 카드 번호를 받지 않습니다.'],['4. 정보 이용','서비스 제공과 보안, 구독 처리, 문의 대응, 성능 개선, 악용 방지 및 요청한 업데이트 발송에 이용합니다.'],['5. 공유 및 보관','호스팅, 인증, 분석, 처리 및 결제를 돕는 제공업체와 필요한 정보를 공유합니다. 필요한 기간 동안만 보관합니다.'],['6. 선택 및 문의','PictTool 피드백 양식으로 계정 정보의 열람·삭제를 요청하고 마케팅 이메일의 수신 거부 링크를 이용할 수 있습니다.']]),
      ar:t('توضح هذه السياسة كيفية تعامل PictTool مع المعلومات عند استخدام موقعنا وخدماتنا.',[['1. المعلومات التي نجمعها','قد نجمع بريدك الإلكتروني عند إنشاء حساب أو استخدامه أو الاشتراك في التحديثات أو إرسال الملاحظات أو شراء Pict Pro. وقد نجمع معلومات تقنية أساسية مثل المتصفح والجهاز واللغة والموقع التقريبي وأحداث الاستخدام.'],['2. الصور والمطالبات','تتم معالجة الصور والمطالبات لتوفير الأداة المطلوبة. لا نستخدم الصور المرفوعة لتحديد هويتك ولا نبيعها. لا ترفع محتوى حساساً أو شخصياً أو سرياً.'],['3. المدفوعات','يتولى Paddle المدفوعات والاشتراكات وقد يعالج بيانات الدفع والفوترة والمعاملات وفق سياسة الخصوصية الخاصة به. لا يتلقى PictTool رقم بطاقتك الكامل.'],['4. استخدام المعلومات','نستخدم المعلومات لتقديم الخدمة وتأمينها، ومعالجة الاشتراكات، والرد على الطلبات، وتحسين الأداء، ومنع إساءة الاستخدام، وإرسال التحديثات المطلوبة.'],['5. المشاركة والاحتفاظ','نشارك المعلومات اللازمة مع مزودي الخدمات الذين يساعدوننا في الاستضافة والمصادقة والتحليل والمعالجة والفوترة. نحتفظ بها للمدة اللازمة بشكل معقول فقط.'],['6. اختياراتك والتواصل','يمكنك طلب الوصول إلى معلومات الحساب أو حذفها عبر نموذج ملاحظات PictTool، وإلغاء رسائل التسويق من خلال رابط إلغاء الاشتراك.']]),
      de:t('Diese Richtlinie erklärt, wie PictTool Informationen bei der Nutzung unserer Website und Dienste verarbeitet.',[['1. Erhobene Informationen','Wir können Ihre E-Mail-Adresse bei Kontoerstellung, Nutzung, Newsletter-Anmeldung, Feedback oder dem Kauf von Pict Pro erheben. Auch grundlegende technische Daten wie Browser, Gerät, Sprache, ungefährer Standort und Nutzungsereignisse können erfasst werden.'],['2. Bilder und Eingaben','Bilder und Eingaben werden zur Bereitstellung der gewünschten Funktion verarbeitet. Wir nutzen hochgeladene Bilder nicht zur Identifizierung und verkaufen sie nicht. Laden Sie keine sensiblen oder vertraulichen Inhalte hoch.'],['3. Zahlungen','Zahlungen und Abonnements werden von Paddle verarbeitet. PictTool erhält nicht Ihre vollständige Kartennummer.'],['4. Verwendung','Wir verwenden Informationen zur Bereitstellung und Sicherung des Dienstes, zur Abonnementverarbeitung, Beantwortung von Anfragen, Verbesserung, Missbrauchsprävention und für angeforderte Updates.'],['5. Weitergabe und Speicherung','Notwendige Informationen werden mit Dienstleistern für Hosting, Authentifizierung, Analyse, Verarbeitung und Abrechnung geteilt. Wir speichern sie nur so lange wie angemessen erforderlich.'],['6. Ihre Wahlmöglichkeiten','Über das Feedback-Formular können Sie Auskunft oder Löschung Ihres Kontos verlangen und Marketing-E-Mails über den Abmeldelink abbestellen.']])
    },
    refund:{
      en:t('This Refund Policy applies to Pict Pro subscriptions purchased through Paddle.',[['1. Cancellation','You may cancel your subscription at any time. Cancellation stops the next renewal; you can continue using the service until the end of the current billing period unless otherwise stated.'],['2. Refunds','If you are not satisfied with your first Pict Pro purchase, you may request a refund within 7 days of the initial charge. Renewal refunds are reviewed case by case. Unless required by law, partial-period refunds are not provided after renewal starts.'],['3. How to request a refund','Use the PictTool feedback form and include the account email, charge date, and a brief reason. Paddle may process the refund and may ask for transaction details.'],['4. Processing time','Approved refunds are returned to the original payment method. Processing time depends on Paddle and your payment provider.']]),
      zh:t('本退款政策适用于通过 Paddle 购买的 Pict Pro 订阅。',[['1. 取消订阅','您可以随时取消订阅。取消后不会产生下一次续费；除非另有说明，您可以继续使用服务直到当前计费周期结束。'],['2. 退款','如果您对首次购买的 Pict Pro 不满意，可以在首次扣款后的 7 天内申请退款。续费订单的退款将逐案审核。除非法律要求，续费开始后通常不提供按剩余时间计算的部分退款。'],['3. 如何申请退款','请使用 PictTool 反馈表单，并提供购买账户邮箱、扣款日期和简要原因。退款可能由 Paddle 处理，并可能需要交易详情。'],['4. 处理时间','获批准的退款将退回原支付方式。到账时间取决于 Paddle 和您的支付服务商。']]),
      es:t('Esta política se aplica a las suscripciones Pict Pro compradas mediante Paddle.',[['1. Cancelación','Puede cancelar en cualquier momento. La cancelación detiene la próxima renovación y puede seguir usando el servicio hasta el final del periodo actual, salvo indicación contraria.'],['2. Reembolsos','Si no está satisfecho con su primera compra, puede solicitar un reembolso dentro de los 7 días del cargo inicial. Los reembolsos de renovaciones se revisan caso por caso.'],['3. Cómo solicitarlo','Use el formulario de comentarios e incluya el correo de la cuenta, la fecha del cargo y el motivo. Paddle puede procesar el reembolso y solicitar datos de la transacción.'],['4. Plazo','Los reembolsos aprobados se devuelven al método de pago original. El plazo depende de Paddle y del proveedor de pago.']]),
      fr:t('Cette politique s’applique aux abonnements Pict Pro achetés via Paddle.',[['1. Résiliation','Vous pouvez résilier à tout moment. La résiliation empêche le prochain renouvellement, mais vous pouvez utiliser le service jusqu’à la fin de la période en cours, sauf indication contraire.'],['2. Remboursements','Si votre premier achat ne vous satisfait pas, vous pouvez demander un remboursement dans les 7 jours suivant le débit initial. Les remboursements de renouvellement sont examinés au cas par cas.'],['3. Demande','Utilisez le formulaire de commentaires avec l’e-mail du compte, la date du débit et la raison. Paddle peut traiter le remboursement et demander des détails.'],['4. Délai','Les remboursements approuvés sont retournés au moyen de paiement d’origine. Le délai dépend de Paddle et du prestataire.']]),
      pt:t('Esta política aplica-se às assinaturas Pict Pro compradas pelo Paddle.',[['1. Cancelamento','Você pode cancelar a qualquer momento. O cancelamento interrompe a próxima renovação, mas você pode continuar usando o serviço até o fim do período atual, salvo indicação contrária.'],['2. Reembolsos','Se não estiver satisfeito com a primeira compra, pode solicitar reembolso em até 7 dias da cobrança inicial. Reembolsos de renovação são analisados caso a caso.'],['3. Como solicitar','Use o formulário de feedback e informe o e-mail da conta, a data da cobrança e o motivo. O Paddle pode processar o reembolso e pedir detalhes da transação.'],['4. Prazo','Reembolsos aprovados retornam ao método de pagamento original. O prazo depende do Paddle e do provedor.']]),
      ja:t('この返金ポリシーは、Paddle を通じて購入した Pict Pro サブスクリプションに適用されます。',[['1. 解約','サブスクリプションはいつでも解約できます。解約すると次回更新が停止され、特に定めがない限り現在の請求期間終了まで利用できます。'],['2. 返金','初回購入に満足できない場合、初回請求から7日以内に返金を申請できます。更新分の返金は個別に審査します。'],['3. 申請方法','PictTool のフィードバックフォームから、アカウントのメール、請求日、理由を送ってください。Paddle が返金を処理し、取引情報を求めることがあります。'],['4. 処理期間','承認された返金は元の支払方法に戻されます。期間は Paddle と決済事業者によって異なります。']]),
      ko:t('이 환불 정책은 Paddle을 통해 구매한 Pict Pro 구독에 적용됩니다.',[['1. 취소','언제든 구독을 취소할 수 있습니다. 취소하면 다음 갱신이 중단되며 별도 안내가 없으면 현재 결제 기간이 끝날 때까지 이용할 수 있습니다.'],['2. 환불','첫 구매에 만족하지 못한 경우 최초 결제 후 7일 이내에 환불을 요청할 수 있습니다. 갱신 결제 환불은 사례별로 검토합니다.'],['3. 신청 방법','피드백 양식에 계정 이메일, 결제일 및 간단한 사유를 적어 주세요. Paddle이 환불을 처리하며 거래 정보를 요청할 수 있습니다.'],['4. 처리 기간','승인된 환불은 원래 결제 수단으로 반환됩니다. 처리 기간은 Paddle과 결제 제공업체에 따라 다릅니다.']]),
      ar:t('تنطبق سياسة رد الأموال هذه على اشتراكات Pict Pro التي تم شراؤها عبر Paddle.',[['1. الإلغاء','يمكنك إلغاء الاشتراك في أي وقت. يوقف الإلغاء التجديد التالي، ويمكنك الاستمرار في استخدام الخدمة حتى نهاية فترة الفوترة الحالية ما لم يذكر خلاف ذلك.'],['2. رد الأموال','إذا لم تكن راضياً عن أول عملية شراء، يمكنك طلب رد الأموال خلال 7 أيام من الخصم الأول. تتم مراجعة طلبات تجديد الاشتراك كل حالة على حدة.'],['3. طريقة الطلب','استخدم نموذج ملاحظات PictTool وأدرج بريد الحساب وتاريخ الخصم والسبب. قد يعالج Paddle الطلب ويطلب تفاصيل المعاملة.'],['4. المدة','تُعاد المبالغ الموافق عليها إلى طريقة الدفع الأصلية. تعتمد المدة على Paddle ومزود الدفع.']]),
      de:t('Diese Richtlinie gilt für über Paddle gekaufte Pict-Pro-Abonnements.',[['1. Kündigung','Sie können jederzeit kündigen. Die Kündigung verhindert die nächste Verlängerung; bis zum Ende des laufenden Abrechnungszeitraums können Sie den Dienst weiter nutzen, sofern nichts anderes gilt.'],['2. Erstattungen','Wenn Sie mit dem ersten Kauf nicht zufrieden sind, können Sie innerhalb von 7 Tagen nach der ersten Abbuchung eine Erstattung verlangen. Erstattungen für Verlängerungen werden einzeln geprüft.'],['3. Antrag','Nutzen Sie das PictTool-Feedback-Formular und nennen Sie Konto-E-Mail, Abbuchungsdatum und Grund. Paddle kann die Erstattung bearbeiten und Transaktionsdaten anfordern.'],['4. Bearbeitungszeit','Genehmigte Erstattungen werden auf die ursprüngliche Zahlungsart zurückgebucht. Die Dauer hängt von Paddle und dem Zahlungsanbieter ab.']])
    }
  };
  window.PICT_LEGAL_I18N={common,policies};
})();

(function(){
  const page=location.pathname.includes('/privacy')?'privacy':location.pathname.includes('/refund')?'refund':'terms';
  const qs=new URLSearchParams(location.search);let lang=qs.get('lang')||localStorage.getItem('pict-language')||'en';
  const data=window.PICT_LEGAL_I18N;const copy=data.common[lang]||data.common.en;const policy=data.policies[page][lang]||data.policies[page].en;
  document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';
  const header=document.querySelector('header');if(header){header.querySelector('a').textContent=copy.home;header.querySelector('h1').textContent=copy[page];header.querySelector('.updated').textContent=copy.updated;}
  const card=document.querySelector('.card');if(card)card.innerHTML='<p>'+policy.intro+'</p>'+policy.sections.map(s=>'<h2>'+s[0]+'</h2><p>'+s[1]+'</p>').join('');
  const footer=document.querySelector('footer');const links={terms:[['privacy',copy.privacy],['refund',copy.refund]],privacy:[['terms',copy.terms],['refund',copy.refund]],refund:[['terms',copy.terms],['privacy',copy.privacy]]}[page];if(footer)footer.innerHTML=links.map(x=>'<a href="../'+x[0]+'/?lang='+lang+'">'+x[1]+'</a>').join(' · ');
})();
